# -*- coding: utf-8 -*-
task :default => :paper

def latexmk_cmd(target, options = nil)
  # "Since minted makes calls to the outside world (i.e. Pygments), you need to
  # tell the LaTeX processor about this by passing it the -shell-escape option
  # or it won’t allow such calls."
  engine = "pdflatex"

  # xelatex is said to be more stable than lualatex and ShareLaTeX does not
  # offer the latter.
  # http://tex.stackexchange.com/a/111625
  # engine = "xelatex"
  # engine = "lualatex"

  # -f     Force latexmk to continue document processing despite errors.
  "latexmk -pvc -pdf -pdflatex='#{engine} -file-line-error -halt-on-error -shell-escape %O %S' #{target}.tex"
end

desc "Generate the PDF of the paper"
task(:paper => :clean) { system(latexmk_cmd("paper")) }

desc "Embed code from external files into LaTeX source"
task(:embed_code) { system("ruby scripts/compute_positions.rb") }

desc "Generate the PDF of paper-no-appendix"
task(:paperna => :clean) { system(latexmk_cmd("paper-no-appendix")) }

desc "Generate the PDF for supplementary materials"
task(:supp) { system(latexmk_cmd("supplementary_materials"))}

desc "Clean"
task(:clean => :git_clean) { system("latexmk -c") }

# Remove only files ignored by Git (not including untracked file)
task(:git_clean) { system("git clean -Xf") }
