# -*- coding: utf-8 -*-

task :default => :paper

desc "Make the paper"
task :paper do
  # From the documentation of the minted package:
  # "Since minted makes calls to the outside world (i.e. Pygments), you need to
  # tell the LaTeX processor about this by passing it the -shell-escape option
  # or it won’t allow such calls."
  latex_options = %w(-shell-escape)
  filenames     = Dir["sections/*.tex"]
  # system("runhaskell Include.hs #{filenames.join(' ')} && pdflatex #{latex_options.join(' ')} main.tex")
  system("pdflatex #{latex_options.join(' ')} main.tex")
end

desc "Update Include.hs from GitHub"
task :update do
  system("curl -OL https://raw.githubusercontent.com/zhiyuanshi/include/master/Include.hs")
end

desc "Remove generated Java source files"
task :clean do
  system("rm -f ../src/*.java")
end
