# -*- coding: utf-8 -*-
task :default => :paper

desc "Prepare rules"
  task :prepare_rules do
    system <<-SHELL
cd rules &&
cp trans-get.tex fi-get.tex &&
cp trans-put.tex fi-put.tex &&
cp trans-sub.tex fi-sub.tex &&
cp trans-typing.tex fi-typing.tex &&
sed -i 's/\\optional/\\optionalnothing/g' fi-*.tex &&
sed -i 's/\\yields/\\yieldsnothing/g'     fi-*.tex &&
cd -
    SHELL
end

def latexmk_cmd(options = "")
  # "Since minted makes calls to the outside world (i.e. Pygments), you need to
  # tell the LaTeX processor about this by passing it the -shell-escape option
  # or it won’t allow such calls."
  "latexmk #{options} -pdf -pdflatex='pdflatex -shell-escape %O %S' main.tex"
end

desc "Generate the PDF of the paper"
task(:paper => :prepare_rules) { system(latexmk_cmd) }

desc "Watch for changes and re-generate the PDF if necessary"
task(:watch) { system(latexmk_cmd("-pvc")) }

desc "Clean"
task(:clean) { system("latexmk -c") }
